import { IMovieTypes } from "../../types";

export const SongsData: IMovieTypes[] = [
  {
    id: 1,
    title: "Kesariya",
    release_year: 2022,
    release_date: "2022-07-17",
    genre: ["Romantic", "Bollywood"],
    language: "Hindi",
    duration_seconds: 269,
    rating: "U",
    popularity: 9.1,
    artist: "Arijit Singh",
    album: "Brahmastra",
    description: "A soulful romantic track expressing deep love and emotions.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/9/9f/Kesariya_song.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example1",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 2,
    title: "Apna Bana Le",
    release_year: 2022,
    release_date: "2022-11-10",
    genre: ["Romantic", "Melody"],
    language: "Hindi",
    duration_seconds: 245,
    rating: "U",
    popularity: 8.9,
    artist: "Arijit Singh",
    album: "Bhediya",
    description: "A soft romantic song expressing unconditional love.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/5/50/Apna_Bana_Le.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example2",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 3,
    title: "Tum Hi Ho",
    release_year: 2013,
    release_date: "2013-04-16",
    genre: ["Romantic", "Sad"],
    language: "Hindi",
    duration_seconds: 262,
    rating: "U",
    popularity: 9.6,
    artist: "Arijit Singh",
    album: "Aashiqui 2",
    description: "A heart-touching love ballad.",
    poster_url: "https://upload.wikimedia.org/wikipedia/en/4/40/Tum_Hi_Ho.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example3",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 4,
    title: "Raataan Lambiyan",
    release_year: 2021,
    release_date: "2021-07-29",
    genre: ["Romantic", "Bollywood"],
    language: "Hindi",
    duration_seconds: 230,
    rating: "U",
    popularity: 8.7,
    artist: "Jubin Nautiyal, Asees Kaur",
    album: "Shershaah",
    description: "A love song about long nights of separation.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/4/49/Raataan_Lambiyan.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example4",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 5,
    title: "Tera Ban Jaunga",
    release_year: 2019,
    release_date: "2019-07-05",
    genre: ["Romantic"],
    language: "Hindi",
    duration_seconds: 245,
    rating: "U",
    popularity: 8.8,
    artist: "Akhil Sachdeva",
    album: "Kabir Singh",
    description: "A passionate love track.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/7/7f/Tera_Ban_Jaunga.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example5",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 6,
    title: "Shayad",
    release_year: 2020,
    release_date: "2020-02-14",
    genre: ["Romantic"],
    language: "Hindi",
    duration_seconds: 250,
    rating: "U",
    popularity: 8.9,
    artist: "Arijit Singh",
    album: "Love Aaj Kal",
    description: "A song about unspoken love.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/6/63/Shayad_Song.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example6",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 7,
    title: "Dil Diyan Gallan",
    release_year: 2017,
    release_date: "2017-12-12",
    genre: ["Romantic"],
    language: "Hindi",
    duration_seconds: 248,
    rating: "U",
    popularity: 8.7,
    artist: "Atif Aslam",
    album: "Tiger Zinda Hai",
    description: "A romantic melody between two lovers.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/0/0f/Dil_Diyan_Gallan.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example7",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 8,
    title: "Channa Mereya",
    release_year: 2016,
    release_date: "2016-09-30",
    genre: ["Sad", "Romantic"],
    language: "Hindi",
    duration_seconds: 290,
    rating: "U",
    popularity: 9.3,
    artist: "Arijit Singh",
    album: "Ae Dil Hai Mushkil",
    description: "A heartbreaking love song.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/2/2c/Channa_Mereya.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example8",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 9,
    title: "Gerua",
    release_year: 2015,
    release_date: "2015-11-18",
    genre: ["Romantic"],
    language: "Hindi",
    duration_seconds: 265,
    rating: "U",
    popularity: 8.8,
    artist: "Arijit Singh, Antara Mitra",
    album: "Dilwale",
    description: "A melodious romantic duet.",
    poster_url: "https://upload.wikimedia.org/wikipedia/en/5/5a/Gerua.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example9",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 10,
    title: "Agar Tum Saath Ho",
    release_year: 2015,
    release_date: "2015-10-16",
    genre: ["Romantic", "Sad"],
    language: "Hindi",
    duration_seconds: 300,
    rating: "U",
    popularity: 9.4,
    artist: "Arijit Singh, Alka Yagnik",
    album: "Tamasha",
    description: "A song about emotional separation.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/4/4c/Agar_Tum_Saath_Ho.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example10",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 11,
    title: "Shape of You",
    release_year: 2017,
    release_date: "2017-01-06",
    genre: ["Pop"],
    language: "English",
    duration_seconds: 234,
    rating: "U",
    popularity: 9.7,
    artist: "Ed Sheeran",
    album: "Divide",
    description: "A catchy modern pop song.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/b/b4/Shape_Of_You.png",
    trailer_url: "https://www.youtube.com/watch?v=example11",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 12,
    title: "Perfect",
    release_year: 2017,
    release_date: "2017-09-26",
    genre: ["Pop", "Romantic"],
    language: "English",
    duration_seconds: 263,
    rating: "U",
    popularity: 9.4,
    artist: "Ed Sheeran",
    album: "Divide",
    description: "A beautiful romantic ballad.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/8/8f/Perfect_Song.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example12",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 13,
    title: "Blinding Lights",
    release_year: 2020,
    release_date: "2020-03-20",
    genre: ["Pop"],
    language: "English",
    duration_seconds: 200,
    rating: "U",
    popularity: 9.5,
    artist: "The Weeknd",
    album: "After Hours",
    description: "An energetic pop track.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/a/a1/Blinding_Lights.png",
    trailer_url: "https://www.youtube.com/watch?v=example13",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 14,
    title: "Levitating",
    release_year: 2020,
    release_date: "2020-10-01",
    genre: ["Pop", "Dance"],
    language: "English",
    duration_seconds: 203,
    rating: "U",
    popularity: 9.0,
    artist: "Dua Lipa",
    album: "Future Nostalgia",
    description: "A disco-pop dance anthem.",
    poster_url: "https://upload.wikimedia.org/wikipedia/en/3/3e/Levitating.png",
    trailer_url: "https://www.youtube.com/watch?v=example14",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 15,
    title: "Senorita",
    release_year: 2019,
    release_date: "2019-06-21",
    genre: ["Pop", "Romantic"],
    language: "English",
    duration_seconds: 191,
    rating: "U",
    popularity: 9.2,
    artist: "Shawn Mendes, Camila Cabello",
    album: "Single",
    description: "A Latin-pop romantic duet.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/6/6b/Se%C3%B1orita_Song.png",
    trailer_url: "https://www.youtube.com/watch?v=example15",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 16,
    title: "Havana",
    release_year: 2018,
    release_date: "2018-01-12",
    genre: ["Pop"],
    language: "English",
    duration_seconds: 217,
    rating: "U",
    popularity: 9.1,
    artist: "Camila Cabello",
    album: "Camila",
    description: "A Latin-inspired pop hit.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/0/0a/Havana_single_cover.png",
    trailer_url: "https://www.youtube.com/watch?v=example16",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 17,
    title: "Believer",
    release_year: 2017,
    release_date: "2017-02-01",
    genre: ["Rock", "Pop"],
    language: "English",
    duration_seconds: 204,
    rating: "U",
    popularity: 9.3,
    artist: "Imagine Dragons",
    album: "Evolve",
    description: "An energetic motivational song.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/b/bd/Imagine_Dragons_Believer.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example17",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 18,
    title: "Closer",
    release_year: 2016,
    release_date: "2016-07-29",
    genre: ["Pop", "EDM"],
    language: "English",
    duration_seconds: 244,
    rating: "U",
    popularity: 9.0,
    artist: "The Chainsmokers",
    album: "Collage",
    description: "A popular EDM love song.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/1/1f/Closer_%28song%29.png",
    trailer_url: "https://www.youtube.com/watch?v=example18",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 19,
    title: "Cheap Thrills",
    release_year: 2016,
    release_date: "2016-02-11",
    genre: ["Pop"],
    language: "English",
    duration_seconds: 218,
    rating: "U",
    popularity: 8.8,
    artist: "Sia",
    album: "This Is Acting",
    description: "A feel-good party song.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/f/f6/Cheap_Thrills.png",
    trailer_url: "https://www.youtube.com/watch?v=example19",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 20,
    title: "Attention",
    release_year: 2017,
    release_date: "2017-04-21",
    genre: ["Pop"],
    language: "English",
    duration_seconds: 211,
    rating: "U",
    popularity: 8.7,
    artist: "Charlie Puth",
    album: "Voicenotes",
    description: "A catchy pop breakup song.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/4/45/Attention_%28song%29.png",
    trailer_url: "https://www.youtube.com/watch?v=example20",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 21,
    title: "Counting Stars",
    release_year: 2013,
    release_date: "2013-06-14",
    genre: ["Pop", "Rock"],
    language: "English",
    duration_seconds: 257,
    rating: "U",
    popularity: 9.2,
    artist: "OneRepublic",
    album: "Native",
    description: "A motivational pop-rock hit.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/d/d2/Counting_Stars.png",
    trailer_url: "https://www.youtube.com/watch?v=example21",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 22,
    title: "Roar",
    release_year: 2013,
    release_date: "2013-08-10",
    genre: ["Pop"],
    language: "English",
    duration_seconds: 224,
    rating: "U",
    popularity: 9.0,
    artist: "Katy Perry",
    album: "Prism",
    description: "A powerful motivational anthem.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/4/47/Katy_Perry_-_Roar.png",
    trailer_url: "https://www.youtube.com/watch?v=example22",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 23,
    title: "Uptown Funk",
    release_year: 2014,
    release_date: "2014-11-10",
    genre: ["Funk", "Pop"],
    language: "English",
    duration_seconds: 270,
    rating: "U",
    popularity: 9.5,
    artist: "Mark Ronson, Bruno Mars",
    album: "Uptown Special",
    description: "A high-energy funky dance track.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/7/7c/Uptown_Funk.png",
    trailer_url: "https://www.youtube.com/watch?v=example23",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 24,
    title: "Faded",
    release_year: 2015,
    release_date: "2015-12-03",
    genre: ["EDM"],
    language: "English",
    duration_seconds: 212,
    rating: "U",
    popularity: 9.1,
    artist: "Alan Walker",
    album: "Different World",
    description: "A melancholic electronic dance hit.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/3/3c/Alan_Walker_-_Faded.png",
    trailer_url: "https://www.youtube.com/watch?v=example24",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 25,
    title: "Alone",
    release_year: 2016,
    release_date: "2016-12-02",
    genre: ["EDM"],
    language: "English",
    duration_seconds: 222,
    rating: "U",
    popularity: 8.9,
    artist: "Alan Walker",
    album: "Different World",
    description: "A melodic EDM song about loneliness.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/8/88/Alan_Walker_-_Alone.png",
    trailer_url: "https://www.youtube.com/watch?v=example25",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 26,
    title: "Despacito",
    release_year: 2017,
    release_date: "2017-01-13",
    genre: ["Latin", "Pop"],
    language: "Spanish",
    duration_seconds: 229,
    rating: "U",
    popularity: 9.6,
    artist: "Luis Fonsi, Daddy Yankee",
    album: "Vida",
    description: "A globally famous Latin pop song.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/6/6b/Despacito_cover.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example26",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 27,
    title: "Dance Monkey",
    release_year: 2019,
    release_date: "2019-05-10",
    genre: ["Pop"],
    language: "English",
    duration_seconds: 210,
    rating: "U",
    popularity: 9.3,
    artist: "Tones and I",
    album: "The Kids Are Coming",
    description: "A viral pop sensation.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/1/1f/Dance_Monkey.png",
    trailer_url: "https://www.youtube.com/watch?v=example27",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 28,
    title: "Bad Guy",
    release_year: 2019,
    release_date: "2019-03-29",
    genre: ["Pop"],
    language: "English",
    duration_seconds: 194,
    rating: "U",
    popularity: 9.2,
    artist: "Billie Eilish",
    album: "When We All Fall Asleep",
    description: "A dark modern pop hit.",
    poster_url: "https://upload.wikimedia.org/wikipedia/en/7/7e/Bad_Guy.png",
    trailer_url: "https://www.youtube.com/watch?v=example28",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 29,
    title: "Girls Like You",
    release_year: 2018,
    release_date: "2018-05-30",
    genre: ["Pop"],
    language: "English",
    duration_seconds: 235,
    rating: "U",
    popularity: 9.1,
    artist: "Maroon 5",
    album: "Red Pill Blues",
    description: "A soft romantic pop song.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/f/f3/Girls_Like_You.png",
    trailer_url: "https://www.youtube.com/watch?v=example29",
    watch_url: "https://www.spotify.com",
  },
  {
    id: 30,
    title: "Let Me Love You",
    release_year: 2016,
    release_date: "2016-08-05",
    genre: ["Pop", "EDM"],
    language: "English",
    duration_seconds: 215,
    rating: "U",
    popularity: 9.0,
    artist: "DJ Snake, Justin Bieber",
    album: "Encore",
    description: "A popular EDM romantic track.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/1/1e/Let_Me_Love_You.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example30",
    watch_url: "https://www.spotify.com",
  },
];
