import { IMovieTypes } from "../../types";

export const MovieData: IMovieTypes[] = [
  {
    id: 11,
    title: "Pathaan",
    release_year: 2023,
    release_date: "2023-01-25",
    genre: ["Action", "Thriller"],
    language: "Hindi",
    duration_minutes: 146,
    rating: "UA",
    imdb_rating: 5.8,
    director: "Siddharth Anand",
    cast: ["Shah Rukh Khan", "Deepika Padukone"],
    description:
      "An Indian spy takes on a powerful rogue agent threatening national security.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/c/c3/Pathaan_film_poster.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example11",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 12,
    title: "KGF: Chapter 2",
    release_year: 2022,
    release_date: "2022-04-14",
    genre: ["Action", "Drama"],
    language: "Kannada",
    duration_minutes: 168,
    rating: "UA",
    imdb_rating: 8.3,
    director: "Prashanth Neel",
    cast: ["Yash", "Sanjay Dutt"],
    description: "Rocky consolidates his empire while facing powerful enemies.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/d/d0/K.G.F_Chapter_2.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example12",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 13,
    title: "Pushpa: The Rise",
    release_year: 2021,
    release_date: "2021-12-17",
    genre: ["Action", "Crime"],
    language: "Telugu",
    duration_minutes: 179,
    rating: "UA",
    imdb_rating: 7.6,
    director: "Sukumar",
    cast: ["Allu Arjun", "Rashmika Mandanna"],
    description:
      "A laborer rises through the ranks of a red sandalwood smuggling syndicate.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/7/75/Pushpa_-_The_Rise.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example13",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 14,
    title: "Interstellar",
    release_year: 2014,
    release_date: "2014-11-07",
    genre: ["Sci-Fi", "Drama"],
    language: "English",
    duration_minutes: 169,
    rating: "PG-13",
    imdb_rating: 8.7,
    director: "Christopher Nolan",
    cast: ["Matthew McConaughey", "Anne Hathaway"],
    description:
      "Explorers travel through a wormhole in space to save humanity.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/b/bc/Interstellar_film_poster.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example14",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 15,
    title: "Inception",
    release_year: 2010,
    release_date: "2010-07-16",
    genre: ["Sci-Fi", "Thriller"],
    language: "English",
    duration_minutes: 148,
    rating: "PG-13",
    imdb_rating: 8.8,
    director: "Christopher Nolan",
    cast: ["Leonardo DiCaprio", "Joseph Gordon-Levitt"],
    description: "A thief steals information by infiltrating dreams.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/7/7f/Inception_ver3.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example15",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 16,
    title: "The Dark Knight",
    release_year: 2008,
    release_date: "2008-07-18",
    genre: ["Action", "Crime"],
    language: "English",
    duration_minutes: 152,
    rating: "PG-13",
    imdb_rating: 9.0,
    director: "Christopher Nolan",
    cast: ["Christian Bale", "Heath Ledger"],
    description: "Batman faces the Joker in a battle for Gotham's soul.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/8/8a/Dark_Knight.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example16",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 17,
    title: "Avengers: Endgame",
    release_year: 2019,
    release_date: "2019-04-26",
    genre: ["Action", "Sci-Fi"],
    language: "English",
    duration_minutes: 181,
    rating: "PG-13",
    imdb_rating: 8.4,
    director: "Anthony Russo, Joe Russo",
    cast: ["Robert Downey Jr.", "Chris Evans"],
    description: "The Avengers attempt to undo Thanos' devastating snap.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/0/0d/Avengers_Endgame_poster.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example17",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 18,
    title: "Spider-Man: No Way Home",
    release_year: 2021,
    release_date: "2021-12-17",
    genre: ["Action", "Fantasy"],
    language: "English",
    duration_minutes: 148,
    rating: "PG-13",
    imdb_rating: 8.2,
    director: "Jon Watts",
    cast: ["Tom Holland", "Zendaya"],
    description:
      "Spider-Man faces multiverse chaos after his identity is revealed.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/0/00/Spider-Man_No_Way_Home_poster.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example18",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 19,
    title: "Joker",
    release_year: 2019,
    release_date: "2019-10-04",
    genre: ["Drama", "Crime"],
    language: "English",
    duration_minutes: 122,
    rating: "R",
    imdb_rating: 8.4,
    director: "Todd Phillips",
    cast: ["Joaquin Phoenix"],
    description: "A failed comedian descends into madness and chaos.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/e/e1/Joker_%282019_film%29_poster.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example19",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 20,
    title: "Parasite",
    release_year: 2019,
    release_date: "2019-05-30",
    genre: ["Thriller", "Drama"],
    language: "Korean",
    duration_minutes: 132,
    rating: "R",
    imdb_rating: 8.5,
    director: "Bong Joon-ho",
    cast: ["Song Kang-ho"],
    description:
      "A poor family infiltrates a wealthy household with deadly consequences.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/5/53/Parasite_%282019_film%29.png",
    trailer_url: "https://www.youtube.com/watch?v=example20",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 21,
    title: "Everything Everywhere All at Once",
    release_year: 2022,
    release_date: "2022-03-25",
    genre: ["Sci-Fi", "Comedy"],
    language: "English",
    duration_minutes: 139,
    rating: "R",
    imdb_rating: 8.0,
    director: "Daniel Kwan, Daniel Scheinert",
    cast: ["Michelle Yeoh"],
    description: "A woman is pulled into a chaotic multiverse adventure.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/1/1e/Everything_Everywhere_All_at_Once.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example21",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 22,
    title: "Gladiator",
    release_year: 2000,
    release_date: "2000-05-05",
    genre: ["Action", "Drama"],
    language: "English",
    duration_minutes: 155,
    rating: "R",
    imdb_rating: 8.5,
    director: "Ridley Scott",
    cast: ["Russell Crowe"],
    description: "A Roman general seeks revenge after betrayal.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/8/8d/Gladiator_ver1.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example22",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 23,
    title: "Titanic",
    release_year: 1997,
    release_date: "1997-12-19",
    genre: ["Romance", "Drama"],
    language: "English",
    duration_minutes: 195,
    rating: "PG-13",
    imdb_rating: 7.9,
    director: "James Cameron",
    cast: ["Leonardo DiCaprio", "Kate Winslet"],
    description: "A tragic love story aboard the ill-fated Titanic.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/2/22/Titanic_poster.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example23",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 24,
    title: "The Matrix",
    release_year: 1999,
    release_date: "1999-03-31",
    genre: ["Sci-Fi", "Action"],
    language: "English",
    duration_minutes: 136,
    rating: "R",
    imdb_rating: 8.7,
    director: "The Wachowskis",
    cast: ["Keanu Reeves"],
    description: "A hacker discovers reality is a simulated illusion.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/c/c1/The_Matrix_Poster.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example24",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 25,
    title: "Forrest Gump",
    release_year: 1994,
    release_date: "1994-07-06",
    genre: ["Drama", "Romance"],
    language: "English",
    duration_minutes: 142,
    rating: "PG-13",
    imdb_rating: 8.8,
    director: "Robert Zemeckis",
    cast: ["Tom Hanks"],
    description: "A simple man influences history through his life journey.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/6/67/Forrest_Gump_poster.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example25",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 26,
    title: "The Shawshank Redemption",
    release_year: 1994,
    release_date: "1994-09-23",
    genre: ["Drama"],
    language: "English",
    duration_minutes: 142,
    rating: "R",
    imdb_rating: 9.3,
    director: "Frank Darabont",
    cast: ["Tim Robbins", "Morgan Freeman"],
    description: "Hope and friendship flourish inside a harsh prison.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/8/81/ShawshankRedemptionMoviePoster.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example26",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 27,
    title: "Fight Club",
    release_year: 1999,
    release_date: "1999-10-15",
    genre: ["Drama", "Thriller"],
    language: "English",
    duration_minutes: 139,
    rating: "R",
    imdb_rating: 8.8,
    director: "David Fincher",
    cast: ["Brad Pitt", "Edward Norton"],
    description: "An underground fight club spirals into chaos.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/f/fc/Fight_Club_poster.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example27",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 28,
    title: "The Godfather",
    release_year: 1972,
    release_date: "1972-03-24",
    genre: ["Crime", "Drama"],
    language: "English",
    duration_minutes: 175,
    rating: "R",
    imdb_rating: 9.2,
    director: "Francis Ford Coppola",
    cast: ["Marlon Brando", "Al Pacino"],
    description: "The rise of a powerful Italian-American crime family.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/1/1c/Godfather_ver1.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example28",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 29,
    title: "The Lord of the Rings: The Fellowship of the Ring",
    release_year: 2001,
    release_date: "2001-12-19",
    genre: ["Fantasy", "Adventure"],
    language: "English",
    duration_minutes: 178,
    rating: "PG-13",
    imdb_rating: 8.8,
    director: "Peter Jackson",
    cast: ["Elijah Wood", "Ian McKellen"],
    description: "A hobbit begins a journey to destroy a powerful ring.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/8/87/Ringstrilogyposter.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example29",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 30,
    title: "Star Wars: Episode IV – A New Hope",
    release_year: 1977,
    release_date: "1977-05-25",
    genre: ["Sci-Fi", "Adventure"],
    language: "English",
    duration_minutes: 121,
    rating: "PG",
    imdb_rating: 8.6,
    director: "George Lucas",
    cast: ["Mark Hamill", "Harrison Ford"],
    description: "A farm boy joins a rebellion against an evil empire.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/8/87/StarWarsMoviePoster1977.jpg",
    trailer_url: "https://www.youtube.com/watch?v=example30",
    watch_url: "https://www.netflix.com",
  },
];
