import { IMovieTypes } from "../../types";

export const TVShowsData: IMovieTypes[] = [
  {
    id: 201,
    title: "Friends",
    release_year: 1994,
    release_date: "1994-09-22",
    genre: ["Comedy", "Romance"],
    language: "English",
    duration_minutes: 5200,
    rating: "PG",
    imdb_rating: 8.9,
    director: "David Crane",
    cast: ["Jennifer Aniston", "Courteney Cox"],
    description: "Six friends navigate life and love in New York.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/b/bc/Friends_season_one_cast.jpg",
    trailer_url: "https://www.youtube.com/watch?v=LTpmw0Ac6Zs",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 202,
    title: "The Big Bang Theory",
    release_year: 2007,
    release_date: "2007-09-24",
    genre: ["Comedy"],
    language: "English",
    duration_minutes: 6000,
    rating: "PG",
    imdb_rating: 8.2,
    director: "Chuck Lorre",
    cast: ["Jim Parsons", "Johnny Galecki"],
    description: "Nerdy scientists and their hilarious social life.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/0/0f/The_Big_Bang_Theory_season_1.jpg",
    trailer_url: "https://www.youtube.com/watch?v=WBb3fojgW0Q",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 203,
    title: "How I Met Your Mother",
    release_year: 2005,
    release_date: "2005-09-19",
    genre: ["Comedy", "Romance"],
    language: "English",
    duration_minutes: 4500,
    rating: "PG",
    imdb_rating: 8.3,
    director: "Carter Bays",
    cast: ["Josh Radnor", "Neil Patrick Harris"],
    description: "A father tells his kids how he met their mother.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/1/1b/How_I_Met_Your_Mother_season_1.jpg",
    trailer_url: "https://www.youtube.com/watch?v=rhI2OZQ7yqI",
    watch_url: "https://www.hotstar.com",
  },
  {
    id: 204,
    title: "The Office",
    release_year: 2005,
    release_date: "2005-03-24",
    genre: ["Comedy"],
    language: "English",
    duration_minutes: 3800,
    rating: "PG",
    imdb_rating: 8.9,
    director: "Greg Daniels",
    cast: ["Steve Carell", "John Krasinski"],
    description: "Everyday office life with awkward humor.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/8/80/The_Office_US_logo.svg",
    trailer_url: "https://www.youtube.com/watch?v=Vmb1tqYqyII",
    watch_url: "https://www.primevideo.com",
  },
  {
    id: 205,
    title: "Brooklyn Nine-Nine",
    release_year: 2013,
    release_date: "2013-09-17",
    genre: ["Comedy", "Crime"],
    language: "English",
    duration_minutes: 3000,
    rating: "PG",
    imdb_rating: 8.4,
    director: "Dan Goor",
    cast: ["Andy Samberg", "Terry Crews"],
    description: "A quirky police squad solves crimes with humor.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/2/29/Brooklyn_Nine-Nine_Season_1.jpg",
    trailer_url: "https://www.youtube.com/watch?v=8c4qVvK6aZg",
    watch_url: "https://www.netflix.com",
  },

  {
    id: 206,
    title: "Sherlock",
    release_year: 2010,
    release_date: "2010-07-25",
    genre: ["Crime", "Drama"],
    language: "English",
    duration_minutes: 1300,
    rating: "UA",
    imdb_rating: 9.1,
    director: "Steven Moffat",
    cast: ["Benedict Cumberbatch", "Martin Freeman"],
    description: "Modern adaptation of Sherlock Holmes.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/b/b9/Sherlock_titlecard.jpg",
    trailer_url: "https://www.youtube.com/watch?v=qlcWFoNqZHc",
    watch_url: "https://www.netflix.com",
  },

  {
    id: 207,
    title: "Doctor Who",
    release_year: 2005,
    release_date: "2005-03-26",
    genre: ["Sci-Fi", "Adventure"],
    language: "English",
    duration_minutes: 7000,
    rating: "PG",
    imdb_rating: 8.6,
    director: "Russell T Davies",
    cast: ["David Tennant", "Matt Smith"],
    description: "A time-traveling doctor explores the universe.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/4/43/Doctor_Who_2011_logo.svg",
    trailer_url: "https://www.youtube.com/watch?v=fJtoxieq40o",
    watch_url: "https://www.primevideo.com",
  },

  {
    id: 208,
    title: "Grey's Anatomy",
    release_year: 2005,
    release_date: "2005-03-27",
    genre: ["Drama", "Romance"],
    language: "English",
    duration_minutes: 9000,
    rating: "PG",
    imdb_rating: 7.6,
    director: "Shonda Rhimes",
    cast: ["Ellen Pompeo"],
    description: "Lives of doctors inside a busy hospital.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/9/9e/Grey%27s_Anatomy_season_1.jpg",
    trailer_url: "https://www.youtube.com/watch?v=9rU4G6p2krs",
    watch_url: "https://www.hotstar.com",
  },

  {
    id: 209,
    title: "Modern Family",
    release_year: 2009,
    release_date: "2009-09-23",
    genre: ["Comedy"],
    language: "English",
    duration_minutes: 4500,
    rating: "PG",
    imdb_rating: 8.5,
    director: "Christopher Lloyd",
    cast: ["Ed O'Neill", "Sofia Vergara"],
    description: "Three families deal with everyday chaos.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/0/02/Modern_Family_season_1.jpg",
    trailer_url: "https://www.youtube.com/watch?v=pRk0AruM1cM",
    watch_url: "https://www.netflix.com",
  },

  {
    id: 210,
    title: "House",
    release_year: 2004,
    release_date: "2004-11-16",
    genre: ["Drama", "Medical"],
    language: "English",
    duration_minutes: 6000,
    rating: "PG",
    imdb_rating: 8.7,
    director: "David Shore",
    cast: ["Hugh Laurie"],
    description: "A brilliant doctor solves medical mysteries.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/3/3a/House_season_1.jpg",
    trailer_url: "https://www.youtube.com/watch?v=MczMB8nUoB4",
    watch_url: "https://www.primevideo.com",
  },

  /* 20 more records would continue in same format */
];
