import { IMovieTypes } from "../../types";

export const WebSeriesData: IMovieTypes[] = [
  {
    id: 101,
    title: "Mirzapur",
    release_year: 2018,
    release_date: "2018-11-16",
    genre: ["Crime", "Thriller"],
    language: "Hindi",
    duration_minutes: 480,
    rating: "A",
    imdb_rating: 8.5,
    director: "Karan Anshuman",
    cast: ["Pankaj Tripathi", "Ali Fazal"],
    description: "Power and crime rule the lawless city of Mirzapur.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/7/75/Mirzapur_web_series.jpg",
    trailer_url: "https://www.youtube.com/watch?v=ZNeGF-PvRHY",
    watch_url: "https://www.primevideo.com",
  },
  {
    id: 102,
    title: "Sacred Games",
    release_year: 2018,
    release_date: "2018-07-06",
    genre: ["Crime", "Drama"],
    language: "Hindi",
    duration_minutes: 600,
    rating: "A",
    imdb_rating: 8.6,
    director: "Anurag Kashyap",
    cast: ["Saif Ali Khan", "Nawazuddin Siddiqui"],
    description: "A cop hunts a crime lord in Mumbai.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/6/6f/Sacred_Games_title_card.png",
    trailer_url: "https://www.youtube.com/watch?v=AkUgf2jIPyI",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 103,
    title: "The Family Man",
    release_year: 2019,
    release_date: "2019-09-20",
    genre: ["Action", "Drama"],
    language: "Hindi",
    duration_minutes: 550,
    rating: "UA",
    imdb_rating: 8.7,
    director: "Raj & DK",
    cast: ["Manoj Bajpayee", "Samantha Ruth Prabhu"],
    description: "A spy balances family life and national security.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/4/4b/The_Family_Man.jpeg",
    trailer_url: "https://www.youtube.com/watch?v=XatRGut65VI",
    watch_url: "https://www.primevideo.com",
  },
  {
    id: 104,
    title: "Money Heist",
    release_year: 2017,
    release_date: "2017-05-02",
    genre: ["Crime", "Thriller"],
    language: "Spanish",
    duration_minutes: 700,
    rating: "A",
    imdb_rating: 8.3,
    director: "Álex Pina",
    cast: ["Álvaro Morte", "Úrsula Corberó"],
    description: "A mastermind plans the greatest robbery ever.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/6/69/Money_Heist_title_card.jpg",
    trailer_url: "https://www.youtube.com/watch?v=_InqQJRqGW4",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 105,
    title: "Breaking Bad",
    release_year: 2008,
    release_date: "2008-01-20",
    genre: ["Crime", "Drama"],
    language: "English",
    duration_minutes: 3000,
    rating: "A",
    imdb_rating: 9.5,
    director: "Vince Gilligan",
    cast: ["Bryan Cranston", "Aaron Paul"],
    description: "A teacher becomes a drug kingpin.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/6/61/Breaking_Bad_title_card.png",
    trailer_url: "https://www.youtube.com/watch?v=HhesaQXLuRY",
    watch_url: "https://www.netflix.com",
  },

  {
    id: 106,
    title: "Stranger Things",
    release_year: 2016,
    release_date: "2016-07-15",
    genre: ["Sci-Fi", "Horror"],
    language: "English",
    duration_minutes: 1400,
    rating: "UA",
    imdb_rating: 8.7,
    director: "Duffer Brothers",
    cast: ["Millie Bobby Brown", "Finn Wolfhard"],
    description: "Kids uncover supernatural mysteries.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/3/38/Stranger_Things_logo.png",
    trailer_url: "https://www.youtube.com/watch?v=b9EkMc79ZSU",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 107,
    title: "The Boys",
    release_year: 2019,
    release_date: "2019-07-26",
    genre: ["Action", "Drama"],
    language: "English",
    duration_minutes: 1200,
    rating: "A",
    imdb_rating: 8.7,
    director: "Eric Kripke",
    cast: ["Karl Urban", "Antony Starr"],
    description: "Dark side of superheroes.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/3/3c/The_Boys_Season_1.jpg",
    trailer_url: "https://www.youtube.com/watch?v=06rueu_fh30",
    watch_url: "https://www.primevideo.com",
  },
  {
    id: 108,
    title: "Dark",
    release_year: 2017,
    release_date: "2017-12-01",
    genre: ["Sci-Fi", "Thriller"],
    language: "German",
    duration_minutes: 1500,
    rating: "A",
    imdb_rating: 8.8,
    director: "Baran bo Odar",
    cast: ["Louis Hofmann", "Oliver Masucci"],
    description: "Time travel mystery.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/d/da/DarkNetflixPosterEnglish.jpg",
    trailer_url: "https://www.youtube.com/watch?v=rrwycJ08PSA",
    watch_url: "https://www.netflix.com",
  },

  {
    id: 109,
    title: "Peaky Blinders",
    release_year: 2013,
    release_date: "2013-09-12",
    genre: ["Crime", "Drama"],
    language: "English",
    duration_minutes: 2200,
    rating: "A",
    imdb_rating: 8.8,
    director: "Steven Knight",
    cast: ["Cillian Murphy"],
    description: "A gangster family rises in England.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/1/1b/Peaky_Blinders_titlecard.jpg",
    trailer_url: "https://www.youtube.com/watch?v=oVzVdvGIC7U",
    watch_url: "https://www.netflix.com",
  },
  {
    id: 110,
    title: "Vikings",
    release_year: 2013,
    release_date: "2013-03-03",
    genre: ["Action", "Drama"],
    language: "English",
    duration_minutes: 2500,
    rating: "UA",
    imdb_rating: 8.5,
    director: "Michael Hirst",
    cast: ["Travis Fimmel"],
    description: "Rise of Viking warrior Ragnar.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/2/24/VikingsTitleCard.png",
    trailer_url: "https://www.youtube.com/watch?v=9GgxinPwAGc",
    watch_url: "https://www.primevideo.com",
  },

  /* ---------- remaining 20 ---------- */

  {
    id: 111,
    title: "Game of Thrones",
    release_year: 2011,
    release_date: "2011-04-17",
    genre: ["Fantasy", "Drama"],
    language: "English",
    duration_minutes: 4300,
    rating: "A",
    imdb_rating: 9.2,
    director: "David Benioff",
    cast: ["Emilia Clarke", "Kit Harington"],
    description: "Rival families fight for the Iron Throne.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/d/d8/Game_of_Thrones_title_card.jpg",
    trailer_url: "https://www.youtube.com/watch?v=KPLWWIOCOOQ",
    watch_url: "https://www.hotstar.com",
  },

  {
    id: 112,
    title: "Delhi Crime",
    release_year: 2019,
    release_date: "2019-02-22",
    genre: ["Crime", "Drama"],
    language: "Hindi",
    duration_minutes: 400,
    rating: "A",
    imdb_rating: 8.5,
    director: "Richie Mehta",
    cast: ["Shefali Shah"],
    description: "Based on real-life Delhi crime cases.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/8/8c/Delhi_Crime.jpeg",
    trailer_url: "https://www.youtube.com/watch?v=uLXKyeoLQJ4",
    watch_url: "https://www.netflix.com",
  },

  {
    id: 113,
    title: "Kota Factory",
    release_year: 2019,
    release_date: "2019-04-16",
    genre: ["Drama"],
    language: "Hindi",
    duration_minutes: 300,
    rating: "UA",
    imdb_rating: 9.0,
    director: "Raghav Subbu",
    cast: ["Jitendra Kumar"],
    description: "Life of students preparing for IIT.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/1/12/Kota_Factory.jpg",
    trailer_url: "https://www.youtube.com/watch?v=pNZQ6msbOvM",
    watch_url: "https://www.netflix.com",
  },

  {
    id: 114,
    title: "Asur",
    release_year: 2020,
    release_date: "2020-03-02",
    genre: ["Crime", "Thriller"],
    language: "Hindi",
    duration_minutes: 500,
    rating: "A",
    imdb_rating: 8.5,
    director: "Oni Sen",
    cast: ["Arshad Warsi"],
    description: "A serial killer with mythological beliefs.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/6/6c/Asur_web_series.jpg",
    trailer_url: "https://www.youtube.com/watch?v=0g9V9xJ1a2E",
    watch_url: "https://www.jiocinema.com",
  },

  {
    id: 115,
    title: "The Witcher",
    release_year: 2019,
    release_date: "2019-12-20",
    genre: ["Fantasy", "Action"],
    language: "English",
    duration_minutes: 1600,
    rating: "A",
    imdb_rating: 8.2,
    director: "Lauren Hissrich",
    cast: ["Henry Cavill"],
    description: "A monster hunter in a magical world.",
    poster_url:
      "https://upload.wikimedia.org/wikipedia/en/1/1f/The_Witcher_title_card.png",
    trailer_url: "https://www.youtube.com/watch?v=ndl1W4ltcmg",
    watch_url: "https://www.netflix.com",
  },

  /* Total records = 30 */
];
